version: '3'

services:
   mcpe: # container name 
      build: .
      image: lomot/minecraft-bedrock
      ports:
         - 19132:19132 
      volumes:
         - /Users/lomot/temp/mcpe-data:/data 
      restart: on-failure:5 
